import { createFileRoute } from "@tanstack/react-router";
import { createClient } from "@supabase/supabase-js";

/**
 * The scheduled-dispatch worker endpoint.
 *
 * `pg_cron` runs `public.alshrouq_dispatch_due()` every minute; when something
 * is due that function POSTs here through `net.http_post`, carrying a shared
 * secret it reads from Supabase Vault. This route does the work, because the
 * transport, the payload builder, the reconciliation and the safety gate are all
 * TypeScript in this Worker — reimplementing any of them in plpgsql would be a
 * second integration to keep in step with the first.
 *
 * The same shape as `api/cdr-sync`, deliberately: a scheduler holds no Supabase
 * session, so it authenticates with a shared credential compared in constant
 * time, and the endpoint is a **no-op when that credential is unset** so an
 * unconfigured deployment cannot be triggered by a guess.
 *
 * Two credentials are accepted — see `isScheduler`. The bearer service role key
 * is the one the poll uses, because both halves of it are provisioned by the
 * platform and so cannot drift apart the way a hand-copied secret did.
 *
 * `GET` reports state and never dispatches. A scheduler health check must not be
 * able to send a courier by accident.
 *
 * The service-role client is used because the worker acts as no user: the rows
 * it touches were authorised by an agent at scheduling time, and there is no
 * session to carry at 2am.
 */

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json", "cache-control": "no-store" },
  });

/** Length-independent, value-constant comparison. `!==` on a secret leaks its
 *  prefix through timing; this compares every byte either way. */
function secretMatches(provided: string | null, expected: string | undefined): boolean {
  if (!expected || !provided) return false;
  if (provided.length !== expected.length) return false;
  let diff = 0;
  for (let i = 0; i < expected.length; i++) diff |= provided.charCodeAt(i) ^ expected.charCodeAt(i);
  return diff === 0;
}

/**
 * Is this the scheduler, by either accepted credential?
 *
 * ## Two ways in, and why the second one exists
 *
 * `x-alshrouq-scheduler-secret` is the original: a string this deployment holds
 * in `ALSHROUQ_SCHEDULER_SECRET` and the database holds in a vault entry, and
 * the two are kept equal by somebody remembering to. That is exactly how it
 * failed — the vault half was never created, so `alshrouq_dispatch_due()` woke
 * every minute, found nothing to authenticate with, and returned the same `0` an
 * idle minute returns. Nothing was sent for days.
 *
 * `Authorization: Bearer <service role key>` is the second, and it is the one
 * the poll now uses. It is **not a new credential**: this project already runs a
 * cron-driven endpoint on exactly this pattern —
 * `/lovable/email/queue/process`, generated by the platform, whose own comment
 * reads "the pg_cron job sends the service role key as a Bearer token", and
 * whose database side reads that key from a vault entry the platform provisions
 * and rotates. That path is live and returns 200 in production today.
 *
 * Reusing it removes the drift entirely. Both halves of the credential are
 * issued and maintained by the same system, so there is no copy for anyone to
 * forget — which is the actual defect here, not the choice of algorithm.
 *
 * ## It grants no new authority
 *
 * A caller holding the service role key can already write `alshrouq_dispatches`
 * directly, and considerably worse. Being able to ask this endpoint to run a
 * poll is strictly less than that. The production safety gate is untouched and
 * still decides whether any courier is contacted.
 *
 * Both comparisons are constant-time, including the bearer — the platform's own
 * route uses `!==`, which leaks a prefix through timing, and there is no reason
 * to copy that part.
 */
function isScheduler(request: Request): boolean {
  if (
    secretMatches(
      request.headers.get("x-alshrouq-scheduler-secret"),
      process.env.ALSHROUQ_SCHEDULER_SECRET,
    )
  ) {
    return true;
  }

  const auth = request.headers.get("authorization");
  if (!auth || !auth.startsWith("Bearer ")) return false;
  return secretMatches(auth.slice("Bearer ".length).trim(), process.env.SUPABASE_SERVICE_ROLE_KEY);
}

function serviceClient() {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) return null;
  return createClient(url, key, { auth: { persistSession: false } });
}

export const Route = createFileRoute("/api/alshrouq-run-scheduled")({
  server: {
    handlers: {
      /**
       * Health only. Reports whether the endpoint is configured and how many
       * dispatches are waiting — never starts one.
       */
      GET: async ({ request }) => {
        if (!isScheduler(request)) {
          console.warn("[alshrouq] scheduler health check rejected: bad or missing credential");
          return json({ error: "unauthorized" }, 401);
        }

        const supabase = serviceClient();
        if (!supabase) return json({ configured: false, due: null }, 200);

        const { isAlShrouqLiveDispatchEnabled } =
          await import("@/lib/shams-crm/alshrouq-dispatch.server");
        const { count } = await (supabase as any)
          .from("alshrouq_dispatches")
          .select("id", { count: "exact", head: true })
          .eq("dispatch_status", "scheduled")
          .is("cancelled_at", null)
          .lte("scheduled_for", new Date().toISOString());

        return json({
          configured: true,
          due: count ?? 0,
          liveDispatchEnabled: isAlShrouqLiveDispatchEnabled(),
        });
      },

      POST: async ({ request }) => {
        if (!isScheduler(request)) {
          /*
           * A rejected caller is the one event that must never be silent.
           *
           * If the two halves of a credential drift apart, the cron job keeps
           * firing and this endpoint keeps refusing it — and scheduled
           * deliveries simply stop happening, with nothing anywhere saying why.
           * That is not hypothetical: it is what this integration did for days,
           * answering every poll with a 401 nobody was reading.
           *
           * The bearer path exists to make that drift impossible rather than
           * merely visible, since both halves of the service role key are issued
           * by the same system. This line stays for the paths that can still
           * fail — a stale header secret, or a caller that is not the scheduler.
           *
           * Nothing about the credential is logged, including its length.
           */
          console.warn("[alshrouq] scheduler request rejected: bad or missing credential");
          return json({ error: "unauthorized" }, 401);
        }

        const supabase = serviceClient();
        if (!supabase) {
          // Configured to exist but not to work. Distinct from "nothing due".
          console.error(
            "[alshrouq] scheduler not configured: SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY missing",
          );
          return json({ error: "not_configured" }, 503);
        }

        const { runDueAlShrouqDispatches, classifyDispatchFailure } =
          await import("@/lib/shams-crm/alshrouq-scheduler.server");

        try {
          const { isAlShrouqLiveDispatchEnabled } =
            await import("@/lib/shams-crm/alshrouq-dispatch.server");
          const summary = await runDueAlShrouqDispatches(supabase as any);

          /*
           * Counts only. Never a customer, never a credential, never a payload —
           * `RunDueSummary` is integers and a test asserts nothing else reaches
           * it.
           *
           * The gate is stated rather than inferred: `skippedDisabled` already
           * carries it, but "0 accepted" reads identically whether the gate was
           * shut or there was simply nothing to do, and those are opposite
           * operational facts.
           *
           * `job` is stated too. A production alert that says only "a scheduled
           * job failed" sends somebody looking through every cron in the
           * database; this one names itself.
           */
          console.info("[alshrouq] scheduled run", {
            job: "alshrouq-run-scheduled",
            ...summary,
            liveDispatchEnabled: isAlShrouqLiveDispatchEnabled(),
          });
          return json({ ok: true, ...summary });
        } catch (err) {
          /*
           * With per-row isolation inside the worker this should now be reached
           * only by a failure of the run itself — the stale-claim sweep or the
           * due read — rather than by one unreachable CRM, which used to abort
           * the whole batch and answer pg_cron with a 500 every minute.
           *
           * It says which job, and what kind of problem, because "500" on its
           * own was the entire signal an operator had during exactly that
           * incident. The classifier returns fixed sentences and never copies
           * anything out of the error, so no credential or customer detail can
           * reach the log or the response.
           */
          const failure = classifyDispatchFailure(err);
          console.error("[alshrouq] scheduled run failed", {
            job: "alshrouq-run-scheduled",
            category: failure.category,
            retryable: failure.retryable,
            error: (err as Error)?.name ?? "unknown",
          });
          return json({ ok: false, error: "run_failed", category: failure.category }, 500);
        }
      },
    },
  },
});
