/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCspReportRouteImport } from './routes/api/csp-report'
import { Route as ApiCdrSyncRouteImport } from './routes/api/cdr-sync'
import { Route as AppShamsRouteImport } from './routes/_app.shams'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCallCenterRouteImport } from './routes/_app.call-center'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AppOrdersIndexRouteImport } from './routes/_app.orders.index'
import { Route as AppComplaintsIndexRouteImport } from './routes/_app.complaints.index'
import { Route as AppCallsIndexRouteImport } from './routes/_app.calls.index'
import { Route as AppBranchesIndexRouteImport } from './routes/_app.branches.index'
import { Route as ApiAlshrouqRunScheduledRouteImport } from './routes/api.alshrouq.run-scheduled'
import { Route as AppOrdersNewRouteImport } from './routes/_app.orders.new'
import { Route as AppOrdersIdRouteImport } from './routes/_app.orders.$id'
import { Route as AppComplaintsNewRouteImport } from './routes/_app.complaints.new'
import { Route as AppComplaintsIdRouteImport } from './routes/_app.complaints.$id'
import { Route as AppCallsTelesalesRouteImport } from './routes/_app.calls.telesales'
import { Route as AppCallsOverviewRouteImport } from './routes/_app.calls.overview'
import { Route as AppCallsLookupRouteImport } from './routes/_app.calls.lookup'
import { Route as AppCallsDiagnosticsRouteImport } from './routes/_app.calls.diagnostics'
import { Route as AppCallsCustomerCareRouteImport } from './routes/_app.calls.customer-care'
import { Route as AppCallsConfigurationRouteImport } from './routes/_app.calls.configuration'
import { Route as AppBranchesImportRouteImport } from './routes/_app.branches.import'
import { Route as AppAdminYeastarDiagnosticsRouteImport } from './routes/_app.admin.yeastar-diagnostics'
import { Route as AppAdminYeastarRouteImport } from './routes/_app.admin.yeastar'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppAdminShamsDiagnosticsRouteImport } from './routes/_app.admin.shams-diagnostics'
import { Route as AppAdminBranchesRouteImport } from './routes/_app.admin.branches'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicCdrProgressJobIdRouteImport } from './routes/api/public/cdr-progress.$jobId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCspReportRoute = ApiCspReportRouteImport.update({
  id: '/api/csp-report',
  path: '/api/csp-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCdrSyncRoute = ApiCdrSyncRouteImport.update({
  id: '/api/cdr-sync',
  path: '/api/cdr-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShamsRoute = AppShamsRouteImport.update({
  id: '/shams',
  path: '/shams',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCallCenterRoute = AppCallCenterRouteImport.update({
  id: '/call-center',
  path: '/call-center',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppComplaintsIndexRoute = AppComplaintsIndexRouteImport.update({
  id: '/complaints/',
  path: '/complaints/',
  getParentRoute: () => AppRoute,
} as any)
const AppCallsIndexRoute = AppCallsIndexRouteImport.update({
  id: '/calls/',
  path: '/calls/',
  getParentRoute: () => AppRoute,
} as any)
const AppBranchesIndexRoute = AppBranchesIndexRouteImport.update({
  id: '/branches/',
  path: '/branches/',
  getParentRoute: () => AppRoute,
} as any)
const ApiAlshrouqRunScheduledRoute = ApiAlshrouqRunScheduledRouteImport.update({
  id: '/api/alshrouq/run-scheduled',
  path: '/api/alshrouq/run-scheduled',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrdersNewRoute = AppOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppComplaintsNewRoute = AppComplaintsNewRouteImport.update({
  id: '/complaints/new',
  path: '/complaints/new',
  getParentRoute: () => AppRoute,
} as any)
const AppComplaintsIdRoute = AppComplaintsIdRouteImport.update({
  id: '/complaints/$id',
  path: '/complaints/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCallsTelesalesRoute = AppCallsTelesalesRouteImport.update({
  id: '/calls/telesales',
  path: '/calls/telesales',
  getParentRoute: () => AppRoute,
} as any)
const AppCallsOverviewRoute = AppCallsOverviewRouteImport.update({
  id: '/calls/overview',
  path: '/calls/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppCallsLookupRoute = AppCallsLookupRouteImport.update({
  id: '/calls/lookup',
  path: '/calls/lookup',
  getParentRoute: () => AppRoute,
} as any)
const AppCallsDiagnosticsRoute = AppCallsDiagnosticsRouteImport.update({
  id: '/calls/diagnostics',
  path: '/calls/diagnostics',
  getParentRoute: () => AppRoute,
} as any)
const AppCallsCustomerCareRoute = AppCallsCustomerCareRouteImport.update({
  id: '/calls/customer-care',
  path: '/calls/customer-care',
  getParentRoute: () => AppRoute,
} as any)
const AppCallsConfigurationRoute = AppCallsConfigurationRouteImport.update({
  id: '/calls/configuration',
  path: '/calls/configuration',
  getParentRoute: () => AppRoute,
} as any)
const AppBranchesImportRoute = AppBranchesImportRouteImport.update({
  id: '/branches/import',
  path: '/branches/import',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminYeastarDiagnosticsRoute =
  AppAdminYeastarDiagnosticsRouteImport.update({
    id: '/admin/yeastar-diagnostics',
    path: '/admin/yeastar-diagnostics',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminYeastarRoute = AppAdminYeastarRouteImport.update({
  id: '/admin/yeastar',
  path: '/admin/yeastar',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminShamsDiagnosticsRoute =
  AppAdminShamsDiagnosticsRouteImport.update({
    id: '/admin/shams-diagnostics',
    path: '/admin/shams-diagnostics',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminBranchesRoute = AppAdminBranchesRouteImport.update({
  id: '/admin/branches',
  path: '/admin/branches',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCdrProgressJobIdRoute =
  ApiPublicCdrProgressJobIdRouteImport.update({
    id: '/api/public/cdr-progress/$jobId',
    path: '/api/public/cdr-progress/$jobId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/call-center': typeof AppCallCenterRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/shams': typeof AppShamsRoute
  '/api/cdr-sync': typeof ApiCdrSyncRoute
  '/api/csp-report': typeof ApiCspReportRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/branches': typeof AppAdminBranchesRoute
  '/admin/shams-diagnostics': typeof AppAdminShamsDiagnosticsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/admin/yeastar': typeof AppAdminYeastarRoute
  '/admin/yeastar-diagnostics': typeof AppAdminYeastarDiagnosticsRoute
  '/branches/import': typeof AppBranchesImportRoute
  '/calls/configuration': typeof AppCallsConfigurationRoute
  '/calls/customer-care': typeof AppCallsCustomerCareRoute
  '/calls/diagnostics': typeof AppCallsDiagnosticsRoute
  '/calls/lookup': typeof AppCallsLookupRoute
  '/calls/overview': typeof AppCallsOverviewRoute
  '/calls/telesales': typeof AppCallsTelesalesRoute
  '/complaints/$id': typeof AppComplaintsIdRoute
  '/complaints/new': typeof AppComplaintsNewRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/orders/new': typeof AppOrdersNewRoute
  '/api/alshrouq/run-scheduled': typeof ApiAlshrouqRunScheduledRoute
  '/branches/': typeof AppBranchesIndexRoute
  '/calls/': typeof AppCallsIndexRoute
  '/complaints/': typeof AppComplaintsIndexRoute
  '/orders/': typeof AppOrdersIndexRoute
  '/api/public/cdr-progress/$jobId': typeof ApiPublicCdrProgressJobIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/call-center': typeof AppCallCenterRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/shams': typeof AppShamsRoute
  '/api/cdr-sync': typeof ApiCdrSyncRoute
  '/api/csp-report': typeof ApiCspReportRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/branches': typeof AppAdminBranchesRoute
  '/admin/shams-diagnostics': typeof AppAdminShamsDiagnosticsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/admin/yeastar': typeof AppAdminYeastarRoute
  '/admin/yeastar-diagnostics': typeof AppAdminYeastarDiagnosticsRoute
  '/branches/import': typeof AppBranchesImportRoute
  '/calls/configuration': typeof AppCallsConfigurationRoute
  '/calls/customer-care': typeof AppCallsCustomerCareRoute
  '/calls/diagnostics': typeof AppCallsDiagnosticsRoute
  '/calls/lookup': typeof AppCallsLookupRoute
  '/calls/overview': typeof AppCallsOverviewRoute
  '/calls/telesales': typeof AppCallsTelesalesRoute
  '/complaints/$id': typeof AppComplaintsIdRoute
  '/complaints/new': typeof AppComplaintsNewRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/orders/new': typeof AppOrdersNewRoute
  '/api/alshrouq/run-scheduled': typeof ApiAlshrouqRunScheduledRoute
  '/branches': typeof AppBranchesIndexRoute
  '/calls': typeof AppCallsIndexRoute
  '/complaints': typeof AppComplaintsIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/api/public/cdr-progress/$jobId': typeof ApiPublicCdrProgressJobIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_app/call-center': typeof AppCallCenterRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/shams': typeof AppShamsRoute
  '/api/cdr-sync': typeof ApiCdrSyncRoute
  '/api/csp-report': typeof ApiCspReportRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_app/admin/branches': typeof AppAdminBranchesRoute
  '/_app/admin/shams-diagnostics': typeof AppAdminShamsDiagnosticsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/admin/yeastar': typeof AppAdminYeastarRoute
  '/_app/admin/yeastar-diagnostics': typeof AppAdminYeastarDiagnosticsRoute
  '/_app/branches/import': typeof AppBranchesImportRoute
  '/_app/calls/configuration': typeof AppCallsConfigurationRoute
  '/_app/calls/customer-care': typeof AppCallsCustomerCareRoute
  '/_app/calls/diagnostics': typeof AppCallsDiagnosticsRoute
  '/_app/calls/lookup': typeof AppCallsLookupRoute
  '/_app/calls/overview': typeof AppCallsOverviewRoute
  '/_app/calls/telesales': typeof AppCallsTelesalesRoute
  '/_app/complaints/$id': typeof AppComplaintsIdRoute
  '/_app/complaints/new': typeof AppComplaintsNewRoute
  '/_app/orders/$id': typeof AppOrdersIdRoute
  '/_app/orders/new': typeof AppOrdersNewRoute
  '/api/alshrouq/run-scheduled': typeof ApiAlshrouqRunScheduledRoute
  '/_app/branches/': typeof AppBranchesIndexRoute
  '/_app/calls/': typeof AppCallsIndexRoute
  '/_app/complaints/': typeof AppComplaintsIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/api/public/cdr-progress/$jobId': typeof ApiPublicCdrProgressJobIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/call-center'
    | '/dashboard'
    | '/profile'
    | '/reports'
    | '/shams'
    | '/api/cdr-sync'
    | '/api/csp-report'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/branches'
    | '/admin/shams-diagnostics'
    | '/admin/users'
    | '/admin/yeastar'
    | '/admin/yeastar-diagnostics'
    | '/branches/import'
    | '/calls/configuration'
    | '/calls/customer-care'
    | '/calls/diagnostics'
    | '/calls/lookup'
    | '/calls/overview'
    | '/calls/telesales'
    | '/complaints/$id'
    | '/complaints/new'
    | '/orders/$id'
    | '/orders/new'
    | '/api/alshrouq/run-scheduled'
    | '/branches/'
    | '/calls/'
    | '/complaints/'
    | '/orders/'
    | '/api/public/cdr-progress/$jobId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/call-center'
    | '/dashboard'
    | '/profile'
    | '/reports'
    | '/shams'
    | '/api/cdr-sync'
    | '/api/csp-report'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/branches'
    | '/admin/shams-diagnostics'
    | '/admin/users'
    | '/admin/yeastar'
    | '/admin/yeastar-diagnostics'
    | '/branches/import'
    | '/calls/configuration'
    | '/calls/customer-care'
    | '/calls/diagnostics'
    | '/calls/lookup'
    | '/calls/overview'
    | '/calls/telesales'
    | '/complaints/$id'
    | '/complaints/new'
    | '/orders/$id'
    | '/orders/new'
    | '/api/alshrouq/run-scheduled'
    | '/branches'
    | '/calls'
    | '/complaints'
    | '/orders'
    | '/api/public/cdr-progress/$jobId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_app/call-center'
    | '/_app/dashboard'
    | '/_app/profile'
    | '/_app/reports'
    | '/_app/shams'
    | '/api/cdr-sync'
    | '/api/csp-report'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_app/admin/branches'
    | '/_app/admin/shams-diagnostics'
    | '/_app/admin/users'
    | '/_app/admin/yeastar'
    | '/_app/admin/yeastar-diagnostics'
    | '/_app/branches/import'
    | '/_app/calls/configuration'
    | '/_app/calls/customer-care'
    | '/_app/calls/diagnostics'
    | '/_app/calls/lookup'
    | '/_app/calls/overview'
    | '/_app/calls/telesales'
    | '/_app/complaints/$id'
    | '/_app/complaints/new'
    | '/_app/orders/$id'
    | '/_app/orders/new'
    | '/api/alshrouq/run-scheduled'
    | '/_app/branches/'
    | '/_app/calls/'
    | '/_app/complaints/'
    | '/_app/orders/'
    | '/api/public/cdr-progress/$jobId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiCdrSyncRoute: typeof ApiCdrSyncRoute
  ApiCspReportRoute: typeof ApiCspReportRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiAlshrouqRunScheduledRoute: typeof ApiAlshrouqRunScheduledRoute
  ApiPublicCdrProgressJobIdRoute: typeof ApiPublicCdrProgressJobIdRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/csp-report': {
      id: '/api/csp-report'
      path: '/api/csp-report'
      fullPath: '/api/csp-report'
      preLoaderRoute: typeof ApiCspReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cdr-sync': {
      id: '/api/cdr-sync'
      path: '/api/cdr-sync'
      fullPath: '/api/cdr-sync'
      preLoaderRoute: typeof ApiCdrSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/shams': {
      id: '/_app/shams'
      path: '/shams'
      fullPath: '/shams'
      preLoaderRoute: typeof AppShamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/call-center': {
      id: '/_app/call-center'
      path: '/call-center'
      fullPath: '/call-center'
      preLoaderRoute: typeof AppCallCenterRouteImport
      parentRoute: typeof AppRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/complaints/': {
      id: '/_app/complaints/'
      path: '/complaints'
      fullPath: '/complaints/'
      preLoaderRoute: typeof AppComplaintsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calls/': {
      id: '/_app/calls/'
      path: '/calls'
      fullPath: '/calls/'
      preLoaderRoute: typeof AppCallsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/branches/': {
      id: '/_app/branches/'
      path: '/branches'
      fullPath: '/branches/'
      preLoaderRoute: typeof AppBranchesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/alshrouq/run-scheduled': {
      id: '/api/alshrouq/run-scheduled'
      path: '/api/alshrouq/run-scheduled'
      fullPath: '/api/alshrouq/run-scheduled'
      preLoaderRoute: typeof ApiAlshrouqRunScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/orders/new': {
      id: '/_app/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AppOrdersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/$id': {
      id: '/_app/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/complaints/new': {
      id: '/_app/complaints/new'
      path: '/complaints/new'
      fullPath: '/complaints/new'
      preLoaderRoute: typeof AppComplaintsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/complaints/$id': {
      id: '/_app/complaints/$id'
      path: '/complaints/$id'
      fullPath: '/complaints/$id'
      preLoaderRoute: typeof AppComplaintsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calls/telesales': {
      id: '/_app/calls/telesales'
      path: '/calls/telesales'
      fullPath: '/calls/telesales'
      preLoaderRoute: typeof AppCallsTelesalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calls/overview': {
      id: '/_app/calls/overview'
      path: '/calls/overview'
      fullPath: '/calls/overview'
      preLoaderRoute: typeof AppCallsOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calls/lookup': {
      id: '/_app/calls/lookup'
      path: '/calls/lookup'
      fullPath: '/calls/lookup'
      preLoaderRoute: typeof AppCallsLookupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calls/diagnostics': {
      id: '/_app/calls/diagnostics'
      path: '/calls/diagnostics'
      fullPath: '/calls/diagnostics'
      preLoaderRoute: typeof AppCallsDiagnosticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calls/customer-care': {
      id: '/_app/calls/customer-care'
      path: '/calls/customer-care'
      fullPath: '/calls/customer-care'
      preLoaderRoute: typeof AppCallsCustomerCareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calls/configuration': {
      id: '/_app/calls/configuration'
      path: '/calls/configuration'
      fullPath: '/calls/configuration'
      preLoaderRoute: typeof AppCallsConfigurationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/branches/import': {
      id: '/_app/branches/import'
      path: '/branches/import'
      fullPath: '/branches/import'
      preLoaderRoute: typeof AppBranchesImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/yeastar-diagnostics': {
      id: '/_app/admin/yeastar-diagnostics'
      path: '/admin/yeastar-diagnostics'
      fullPath: '/admin/yeastar-diagnostics'
      preLoaderRoute: typeof AppAdminYeastarDiagnosticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/yeastar': {
      id: '/_app/admin/yeastar'
      path: '/admin/yeastar'
      fullPath: '/admin/yeastar'
      preLoaderRoute: typeof AppAdminYeastarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/shams-diagnostics': {
      id: '/_app/admin/shams-diagnostics'
      path: '/admin/shams-diagnostics'
      fullPath: '/admin/shams-diagnostics'
      preLoaderRoute: typeof AppAdminShamsDiagnosticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/branches': {
      id: '/_app/admin/branches'
      path: '/admin/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AppAdminBranchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cdr-progress/$jobId': {
      id: '/api/public/cdr-progress/$jobId'
      path: '/api/public/cdr-progress/$jobId'
      fullPath: '/api/public/cdr-progress/$jobId'
      preLoaderRoute: typeof ApiPublicCdrProgressJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCallCenterRoute: typeof AppCallCenterRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppShamsRoute: typeof AppShamsRoute
  AppAdminBranchesRoute: typeof AppAdminBranchesRoute
  AppAdminShamsDiagnosticsRoute: typeof AppAdminShamsDiagnosticsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminYeastarRoute: typeof AppAdminYeastarRoute
  AppAdminYeastarDiagnosticsRoute: typeof AppAdminYeastarDiagnosticsRoute
  AppBranchesImportRoute: typeof AppBranchesImportRoute
  AppCallsConfigurationRoute: typeof AppCallsConfigurationRoute
  AppCallsCustomerCareRoute: typeof AppCallsCustomerCareRoute
  AppCallsDiagnosticsRoute: typeof AppCallsDiagnosticsRoute
  AppCallsLookupRoute: typeof AppCallsLookupRoute
  AppCallsOverviewRoute: typeof AppCallsOverviewRoute
  AppCallsTelesalesRoute: typeof AppCallsTelesalesRoute
  AppComplaintsIdRoute: typeof AppComplaintsIdRoute
  AppComplaintsNewRoute: typeof AppComplaintsNewRoute
  AppOrdersIdRoute: typeof AppOrdersIdRoute
  AppOrdersNewRoute: typeof AppOrdersNewRoute
  AppBranchesIndexRoute: typeof AppBranchesIndexRoute
  AppCallsIndexRoute: typeof AppCallsIndexRoute
  AppComplaintsIndexRoute: typeof AppComplaintsIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCallCenterRoute: AppCallCenterRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppShamsRoute: AppShamsRoute,
  AppAdminBranchesRoute: AppAdminBranchesRoute,
  AppAdminShamsDiagnosticsRoute: AppAdminShamsDiagnosticsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminYeastarRoute: AppAdminYeastarRoute,
  AppAdminYeastarDiagnosticsRoute: AppAdminYeastarDiagnosticsRoute,
  AppBranchesImportRoute: AppBranchesImportRoute,
  AppCallsConfigurationRoute: AppCallsConfigurationRoute,
  AppCallsCustomerCareRoute: AppCallsCustomerCareRoute,
  AppCallsDiagnosticsRoute: AppCallsDiagnosticsRoute,
  AppCallsLookupRoute: AppCallsLookupRoute,
  AppCallsOverviewRoute: AppCallsOverviewRoute,
  AppCallsTelesalesRoute: AppCallsTelesalesRoute,
  AppComplaintsIdRoute: AppComplaintsIdRoute,
  AppComplaintsNewRoute: AppComplaintsNewRoute,
  AppOrdersIdRoute: AppOrdersIdRoute,
  AppOrdersNewRoute: AppOrdersNewRoute,
  AppBranchesIndexRoute: AppBranchesIndexRoute,
  AppCallsIndexRoute: AppCallsIndexRoute,
  AppComplaintsIndexRoute: AppComplaintsIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiCdrSyncRoute: ApiCdrSyncRoute,
  ApiCspReportRoute: ApiCspReportRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiAlshrouqRunScheduledRoute: ApiAlshrouqRunScheduledRoute,
  ApiPublicCdrProgressJobIdRoute: ApiPublicCdrProgressJobIdRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
