-- RETIRED. This migration is intentionally empty.
--
-- ## What it used to contain, and why it is gone
--
-- It created `sync_order_invoice_flags` and its trigger, then ran a one-time
-- backfill applying that derivation to every order in the table. The identical
-- statement had already shipped as `20260815165443` (a Lovable-applied copy of
-- this same file; the two differed only in comment wording), and **that backfill
-- is what caused the verification incident of 2026-08-15**:
--
--   * it derived `call_center_verified` and `invoices_verified` from
--     `order_activity` rows of type `invoice_verified` / `invoice_value_changed`;
--   * that evidence only began to exist on 2026-08-14 (`20260814140000`), while
--     `call_center_verified` had been a hand-ticked checkbox since 2026-06-24
--     (`20260624110459`);
--   * so every order predating the log joined to nothing, counted zero, and was
--     assigned `false` — not because anything established it was a walk-in, but
--     because nothing had established anything at all.
--
-- 3,837 orders were written in one statement at `2026-08-15 16:54:43.943234+00`
-- and 3,836 lost a flag a person had set. 3,834 were restored from their own
-- `verification_changed` history; the state captured before that restoration is
-- kept in `public.orders_verification_snapshot_20260815`.
--
-- ## Why empty rather than deleted
--
-- The version number stays so the migration chain keeps its shape and ordering,
-- and so this file remains the place anyone looking up `20260815190000` lands.
-- Deleting it would leave the incident's most dangerous artefact explained
-- nowhere. Emptying it means a future `supabase db push` applies a no-op instead
-- of re-running the backfill against a restored database.
--
-- Nothing of value is lost: every object it created is already deployed by
-- `20260815165443`, and the function it defined has since been corrected by
-- `20260815230000`, which adds the `verified_cnt > 0` guard this version lacked.
-- Applying this file's original body today would both re-corrupt the data and
-- revert that guard.
--
-- `20260815165443` is left exactly as applied: it is the historical record of
-- what ran. It cannot execute again on this database — it is already recorded in
-- `supabase_migrations.schema_migrations`. A rebuild from an empty database would
-- replay it, so a rebuild must be followed by `20260815230000`, which the chain
-- already guarantees by ordering.
--
-- See `docs/project.md`, rule 11.
