-- The scheduler stops depending on a credential somebody has to remember.
--
-- ===========================================================================
-- The defect, and why a new secret was never the answer
-- ===========================================================================
-- `alshrouq_dispatch_due()` authenticated to the application with
-- `x-alshrouq-scheduler-secret`: one string held twice, once in the vault and
-- once in the deployment's `ALSHROUQ_SCHEDULER_SECRET`, kept equal by somebody
-- remembering to do it.
--
-- Nobody did. The vault half was never created, so the function reached
-- `IF endpoint IS NULL OR secret IS NULL THEN RETURN 0` on every one of 5,769
-- consecutive `succeeded` cron runs and made no HTTP request at all. A real
-- delivery sat in `scheduled` for days with `attempt_count = 0`. Supplying the
-- missing half would have fixed today's outage and left the mechanism that
-- caused it in place, ready to do the same thing after the next rotation.
--
-- ===========================================================================
-- What replaces it already exists in this database
-- ===========================================================================
-- `public.email_queue_dispatch()` -- the platform's own cron-driven job, live
-- and returning 200 -- authenticates like this:
--
--   'Authorization', 'Bearer ' || (SELECT decrypted_secret
--                                    FROM vault.decrypted_secrets
--                                   WHERE name = 'email_queue_service_role_key')
--
-- and the endpoint it calls, `/lovable/email/queue/process`, compares that
-- token against `process.env.SUPABASE_SERVICE_ROLE_KEY`. Its own comment states
-- the contract: "the pg_cron job sends the service role key as a Bearer token".
--
-- Both halves of that credential are issued and rotated by the platform, on
-- both sides, with nobody copying anything. That is the property the AlShrouq
-- poll was missing, so it now uses the same entry and the same header.
-- `/api/alshrouq-run-scheduled` accepts it through `isScheduler()`, which still
-- accepts the old header too, in constant time, so nothing that works today
-- stops working.
--
-- This grants no new authority. A caller holding the service role key can
-- already write `alshrouq_dispatches` directly and do considerably worse than
-- ask this endpoint to run a poll.
--
-- ===========================================================================
-- What is deliberately unchanged
-- ===========================================================================
--   * The endpoint. `alshrouq_scheduler_url` in the vault, as configured.
--   * The schedule. Every minute, already registered and active.
--   * The safety gate. `ALSHROUQ_LIVE_DISPATCH_ENABLED` still decides alone
--     whether a courier is contacted, and this migration cannot reach it.
--   * The dispatch itself. The poll pokes; it has never sent anything, and the
--     TypeScript worker behind the endpoint remains the only thing that does.
--
-- ===========================================================================
-- Why this file no longer defines the function
-- ===========================================================================
-- It used to. That was the mistake this section records.
--
-- `20260826100000` -- authored earlier, applied later, and carrying the
-- observability, health-state and stale-claim recovery work -- also defines
-- `alshrouq_dispatch_due()`. Two migrations defining one function is a coin
-- toss decided by filename order: `db push` on a fresh database would run
-- `100000` and then this file, and *this* file's simpler body would win,
-- silently discarding the better implementation. Production, having skipped
-- `100000`, would end up with something different again. One branch, two
-- databases, two functions.
--
-- So the definition now lives in exactly one place. `20260826100000` is the
-- authoritative implementation and this file no longer touches the function at
-- all -- not `CREATE OR REPLACE`, not `REVOKE`, not `COMMENT ON FUNCTION`. Its
-- Bearer credential, the reason this migration existed, survives there
-- unchanged; every statement that used to be here is present in that file.
--
-- What remains below is the one thing that is genuinely this migration's own:
-- retiring the credential the old scheme needed.

-- ===========================================================================
-- The credential nobody needs any more
-- ===========================================================================
-- Removed rather than left lying about: an unused secret is one a later reader
-- has to work out the status of, and no function reads it any more -- the
-- authoritative poll in `20260826100000` reads `email_queue_service_role_key`.
-- Nothing else in the schema references this name; it appears only in the two
-- AlShrouq scheduler migrations.
--
-- The *deployment* variable `ALSHROUQ_SCHEDULER_SECRET` is untouched and still
-- works: `isScheduler()` accepts that header from any external caller. This
-- only drops the database's copy, which existed solely for this function.
DELETE FROM vault.secrets WHERE name = 'alshrouq_scheduler_secret';
